parameters:
  - name: service
    type: string

  - name: language
    type: string
    values:
      - dotnet
      - netframework

  - name: command
    type: string
    values:
      - test

  - name: dependsOn
    type: object
    default: ''

stages:
  - template: commands/${{ parameters.command }}.yml
    parameters:
      service: ${{ parameters.service }}
      language: ${{ parameters.language }}
      command: ${{ parameters.command }}
      dependsOn: ${{ parameters.dependsOn }}
