parameters:
  - name: service
    type: string

  - name: command
    type: string

  - name: language
    type: string
    values:
      - dotnet
      - netframework

  - name: projects
    type: object
    default: []

  - name: artifacts
    type: object
    default: []

  - name: dependsOn
    type: object
    default: []

stages:
  - stage: ${{ replace(parameters.service, '-', '_') }}_${{ parameters.command }}_build_publish
    ${{ if ne(length(parameters.dependsOn), 0) }}:
      dependsOn: ${{ parameters.dependsOn }}
    displayName: '🛠️ Build and Publish'
    jobs:
      - template: ../../../jobs/build-publish.yml
        parameters:
          language: ${{ parameters.language }}
          projects: ${{ parameters.projects }}
          artifacts: ${{ parameters.artifacts }}

  - stage: ${{ replace(parameters.service, '-', '_') }}_${{ parameters.command }}_deploy
    displayName: '🚀 Deploy'
    dependsOn: ${{ replace(parameters.service, '-', '_') }}_${{ parameters.command }}_build_publish
    jobs:
      - template: ../../../jobs/download-deploy.yml
        parameters:
          service: ${{ parameters.service }}
          projects: ${{ parameters.projects }}
          artifacts: ${{ parameters.artifacts }}
