parameters:
  - name: language
    type: string
    values:
      - dotnet
      - netframework

jobs:
  - job: build_test
    displayName: '✅ Build and Test'
    steps:
      - checkout: self
        displayName: '📂 Checkout Source Repository'
        clean: true
        fetchDepth: 1
        fetchTags: false
        persistCredentials: false

      - template: ../steps/${{ parameters.language }}/build.yml

      - template: ../steps/${{ parameters.language }}/test.yml
