parameters:
  - name: service
    type: string

  - name: projects
    type: object
    default: []

  - name: artifacts
    type: object
    default: []

jobs:
  - job: download_deploy
    displayName: '🚀 Download and Deploy'
    steps:
      - ${{ if eq(parameters.service, 'nuget') }}:
        - checkout: self
          displayName: '📂 Checkout Source Repository'
          clean: true
          fetchDepth: 0
          fetchTags: true
          persistCredentials: true

      - ${{ else }}:
        - checkout: none

      - template: ../steps/artifact/download.yml
        parameters:
          artifacts: ${{ parameters.artifacts }}

      - ${{ if eq(parameters.service, 'nuget') }}:
        - template: ../steps/gitversion/execute.yml

      - template: ../steps/${{ parameters.service }}/deploy.yml
        parameters:
          projects: ${{ parameters.projects }}
