parameters:
  - name: language
    type: string
    values:
      - dotnet
      - netframework

stages:
  - stage: build_test
    displayName: '🧪 Build and Test'
    jobs:
      - template: ../../../jobs/build-test.yml
        parameters:
          language: ${{ parameters.language }